export { default as Left } from './Left'
export { default as Lock } from './Lock'
export { default as Scoreboard } from './Scoreboard'
export { default as StarFilled } from './StarFilled'
export { default as Star } from './Star'
export { default as Stopwatch } from './Stopwatch'
export { default as Tick } from './Tick'
